### ISSUE TITLE
module is broken on latest xposed.

### ISSUE THREAD

**Issue by Red-M** [zst123/Xposed-ScreenOffAnimation#12]
Hi

This module no longer works on the latest xposed version because it includes the classes for xposed in it.
As per rovo89's changes on xposed [here](http://forum.xda-developers.com/showpost.php?p=66681910&postcount=32) and [here](http://forum.xda-developers.com/showpost.php?p=67658523&postcount=35).

Can we get this fixed please?
@ngxson @zst123 

Thanks.

**Comment by bendwv** [comment]
Why was this closed? Was it fixed?
